### ISSUE TITLE
Missing setup info in the ReadMe

### ISSUE THREAD

**Issue by peteristhegreat** [jordanjambazov/osqa-gplus#5]
Hi jordanjambazov,

I am trying to get this running on a bitnami instance of osqa (osqa-1.0rc-9).  I fixed the extra quotes that were in the buttons.html, but besides that and installing the Google API credentials, I am not seeing anything.  It doesn't look like buttons.html is getting rendered.

I went to console.developers.google.com, created a project, and then went to `APIs & auth > Credentials > Create new Client ID`, and made a client id for a Web Application with the callback to `answers.example.com/oauth2callback`. I downloaded the client_secrets_XXXXX.json and renamed it and placed it in `/opt/bitnami/apps/osqa`.

I tried looking into the log file `/opt/bitnami/apps/osqa/log/django.osqa.log` for what is going on.  The osqa site is pretty active, so I wasn't sure what I should be looking for.

Any thoughts?  Right now most of our users are using Google for logging in, and I want to try to get this working soon.

And I have been restarting the server whenever testing a change in the plugins.

**Comment by marekduciuc** [comment]
Hello,
i have same issue here i have created symlink lek this: 
**ln -s  /usr/local/src/osqa-gplus/gplusauth /usr/local/src/osqa/forum_modules/gplusauth**

but i do not see g+ icon in app  
What should i do ?

**Comment by marekduciuc** [comment]
It was due to missing oauth2client library in may case

**Comment by peteristhegreat** [comment]
I'll give that a try soon and let you know how it goes.  Thanks for posting
what you found.

**Comment by peteristhegreat** [comment]
Additional commands I've had to run to get it to show up and not have errors:

    sudo pip install --upgrade oauth2client
    sudo apt-get install python-dev libldap2-dev libsasl2-dev libssl-dev -y
    sudo pip install python-ldap
    sudo ./opt/bitnami/ctlscript.sh restart

Thanks for the post @marekduciuc , that was very helpful.  Do you know what redirect URL to use when setting it up on the google account side?

**Comment by jordanjambazov** [comment]
Hey @peteristhegreat 

Use the following Redirect URLs in the Google Console Settings.

http://example.com/account/register/
http://localhost:8000/account/register/
http://example.com/account/googleplus/done/
http://localhost:8000/account/googleplus/done/

**Comment by peteristhegreat** [comment]
Awesome!
Just for the record:


https://code.google.com/apis/console

1. Create a project.
2. Go to `APIs & auth > Credentials > OAuth > Create new Client ID`
3. Follow the prompts, and fill in the form appropriately.
4. Select `web application`.
5. Set the Javascript Origin to your website's domain/subdomain, no path, such as `http://example.com/`
6. Set the Redirect URL to `http://example.com/account/googleplus/done/`
7. Download the secret `client_secrets.json`, to upload to your server.
8. The first time setting it up it may take a few minutes for updates to go through all the way.

Great plugin.  Thanks @jordanjambazov .
