### ISSUE TITLE
Empty google button displayed

### ISSUE THREAD

**Issue by vosgaust** [jordanjambazov/osqa-gplus#6]
Hi, I tried to install gplusauth on osqa-1.0rc9 I followed the steps (I had to install oauth2client to get it working) and I'm getting an empty button with no image and no links. I attach a screenshot of my login page:
![screen shot 2015-06-25 at 13 20 52](https://cloud.githubusercontent.com/assets/6062473/8373382/88e86404-1bec-11e5-8a11-f15080f31cc1.png)

Digging into the code, I'm assuming that that empty div should have been filled with the content of templates/button.html but I don't know what I'm missing. Do you have an idea what could be happening?

**Comment by vosgaust** [comment]
I managed to solve this problem by removing an extra quotes in button.html (auth_provider_signin shouldn't be between quotes). But now I get to the google signin screen and the next step, when it redirects to my community, I get a 404 error. Any idea?

**Comment by jordanjambazov** [comment]
@vosgaust Nice to hear that you managed to solve the issue. For some reason you have `osqa` twice in this URL: `http://example.com:80/osqa/osqa/account/googleplus/done/`. Maybe that is the issue?

**Comment by vosgaust** [comment]
@pietroalbini If I try with only one, google gives me an error due to redirect uris discrepancy so the redirect uri that is sent to google api is just like the above.

**Comment by pietroalbini** [comment]
@vosgaust why did you tag me?

**Comment by vosgaust** [comment]
By error, sorry

**Comment by hendrenja** [comment]
Hello @jordanjambazov, I am having a similar problem where the button is not being displayed. Any ideas on this?

This is a fresh install and I have confirmed that the cloned repository has your latest changes..

![osqa_oauth2_bug](https://cloud.githubusercontent.com/assets/14815166/11084957/171d5f5a-8807-11e5-9106-573898ea2e1a.png)
